// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bGXVsYV0jdymS6oUBYGg4P99sk0YUxU',
    appId: '1:850306167553:web:64d87748e67f77a0572100',
    messagingSenderId: '850306167553',
    projectId: 'fir-calculator-9f61b',
    authDomain: 'fir-calculator-9f61b.firebaseapp.com',
    storageBucket: 'fir-calculator-9f61b.firebasestorage.app',
    measurementId: 'G-4R1XCH1KTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGgsKzlRgWbBp4s6TxTnD1tOZx8n07hlY',
    appId: '1:850306167553:android:e1f9ff989ba2d735572100',
    messagingSenderId: '850306167553',
    projectId: 'fir-calculator-9f61b',
    storageBucket: 'fir-calculator-9f61b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7mghRE8anNNf6gURoQA3snKFKWRUbNM',
    appId: '1:850306167553:ios:3f060def6b9b8395572100',
    messagingSenderId: '850306167553',
    projectId: 'fir-calculator-9f61b',
    storageBucket: 'fir-calculator-9f61b.firebasestorage.app',
    iosBundleId: 'main.app.fireCalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr7mghRE8anNNf6gURoQA3snKFKWRUbNM',
    appId: '1:850306167553:ios:3f060def6b9b8395572100',
    messagingSenderId: '850306167553',
    projectId: 'fir-calculator-9f61b',
    storageBucket: 'fir-calculator-9f61b.firebasestorage.app',
    iosBundleId: 'main.app.fireCalc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7bGXVsYV0jdymS6oUBYGg4P99sk0YUxU',
    appId: '1:850306167553:web:92d94f4e6e47d379572100',
    messagingSenderId: '850306167553',
    projectId: 'fir-calculator-9f61b',
    authDomain: 'fir-calculator-9f61b.firebaseapp.com',
    storageBucket: 'fir-calculator-9f61b.firebasestorage.app',
    measurementId: 'G-GMEZLF4NY6',
  );

}